import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Hand-written (not autogenerated) so the reading order is deliberate.
// Every page listed here must exist in docs-users/ - the build fails otherwise.
const sidebars: SidebarsConfig = {
  usersSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/quickstart-docker',
        'getting-started/install-binary',
        'getting-started/first-run',
        'getting-started/organizing-your-library',
        'getting-started/remote-access',
      ],
    },
    {
      type: 'category',
      label: 'Server administration',
      items: [
        'admin/console-tour',
        'admin/libraries',
        'admin/users-and-invites',
        'admin/sharing',
      ],
    },
    {
      type: 'category',
      label: 'Listening',
      items: [
        'listening/connecting',
        'listening/browsing',
        'listening/playback',
        'listening/offline-downloads',
        'listening/account',
        'listening/api-keys',
        'listening/mobile-apps',
      ],
    },
    {
      type: 'category',
      label: 'Desktop manager',
      items: [
        'manager/index',
        'manager/servers',
        'manager/organizing',
        'manager/audible-backup',
      ],
    },
    {
      type: 'category',
      label: 'Community metadata',
      items: ['community/meta-site'],
    },
    'demo',
    'troubleshooting',
    'faq',
  ],
};

export default sidebars;
