import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Hand-written (not autogenerated) so the reading order is deliberate.
// Every page listed here must exist in docs-developers/ - the build fails otherwise.
const sidebars: SidebarsConfig = {
  developersSidebar: [
    'index',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/invariants',
        'architecture/cross-repo-contract',
        'architecture/release-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Server (audiosilo-server)',
      items: [
        'server/overview',
        'server/data-model',
        'server/auth-and-security',
        'server/scanner',
        'server/media',
        'server/web-ui',
        'server/configuration',
        {
          type: 'category',
          label: 'HTTP API',
          items: ['server/api/index', 'server/api/reference'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Player app (audiosilo-frontend)',
      items: [
        'frontend/overview',
        'frontend/playback',
        'frontend/offline',
        'frontend/state-and-data',
        'frontend/i18n',
        'frontend/testing',
      ],
    },
    {
      type: 'category',
      label: 'Desktop manager (audiosilo-manager)',
      items: [
        'manager/overview',
        'manager/server-integration',
        'manager/audible',
        'manager/transfers',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/workspace',
        'contributing/gates-and-ci',
        'contributing/cross-repo-changes',
        'contributing/releasing',
        'contributing/documentation',
      ],
    },
  ],
};

export default sidebars;
